apiVersion: v1
kind: Pod
metadata:
  name: dev-env
  labels:
    dev: dev
spec:
  containers:
    - image: golang:1.14-stretch
      name: dev
      command: ["/bin/sh"]
      args: ["-c", "tail -f /dev/null"]
      volumeMounts:
        - mountPath: /go
          name: volume
  nodeSelector:
    kubernetes.io/os: linux
    node-role.kubernetes.io/master: ""
  volumes:
    - name: volume
      hostPath:
        path: /hom/ubuntu/go
        type: Directory
  tolerations:
    - effect: NoSchedule
      operator: Exists
